version: "3.9"
services:  
  prefect-internal-web-app-code-generator:
    image: test-prefect-internal-web-app-code-generator:test01
    container_name: prefect-internal-web-app-code-generator
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    ports:
      - 192.168.1.127:9090:9090 