services:  
  prefect-internal-web-app-code-generator:
    image: phucdinh/prefect-internal-web-app-code-generator:v1.1.4
    container_name: prefect-internal-web-app-code-generator
    restart: unless-stopped
    env_file:
      - path: ./prod.env
    entrypoint: ./entrypoint.sh
    ports:
      - 9090:9090
    networks:
      - data_tool
    depends_on:
      - superset_api_db
  superset_api_db:
    image: postgres:15
    container_name: superset-api-db
    restart: unless-stopped
    env_file:
      - ./prod.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - data_tool
    ports:
      - 5432
volumes:
  db_data:
networks:
  data_tool:
    name: data_tool
